### ISSUE TITLE
what

### ISSUE THREAD

**Issue by ghost** [ofHillsAndLakes/Project-Juliet-Omicron#11]

**Comment by Coolcoderguy** [comment]
to be honest I did use it at as a reference but... the thing he uses does not compare to the internet, i researched it  before doing it. If you don't believe you can google it. If you guys would like I can create another project. I still want us to be in a group.

**Comment by majestiff** [comment]
You guys can proceed with this project. I have already begun my solo work and just putting the finishing touches. I haven't given the professor any names, and only mentioned that there was a member in the group that I would like to work with but as far as mentioning anyone, it hasn't happened. If you guys haven't received a message on canvas I guess it would be safe to say everything is fine. With that said, good luck with your project.

**Comment by Coolcoderguy** [comment]
so what did you tell the teacher exactly? I really only used it as a reference and was going to change it later, I just wanted to get the skeleton of the project done.
