### ISSUE TITLE
Betting

### ISSUE THREAD

**Issue by ghost** [ofHillsAndLakes/Project-Juliet-Omicron#5]

**Comment by RobertBohlman** [comment]
Right so does anyone have a preference for how the bets will be handled? (Nothing to do with the actual coding, just what system of betting should be used). Or if everyone's indifferent I can just pick something.

**Comment by majestiff** [comment]
We can just do increments of 5, 10, 25, 50, 100. Like at the casinos! :) 

Or, we can keep it simple and easy by just allowing the user to input his bets. :)

**Comment by RobertBohlman** [comment]
I think I'll try a free for all system first, since it wont be too hard to add an ante afterwards.

**Comment by RobertBohlman** [comment]
Well I think I have this mostly done (haven't done anything fancy yet) So I'll be ready to show it off tomorrow. Or I can just upload it now and let you guys have a look?

**Comment by Coolcoderguy** [comment]
you could upload if you want or show us tomorrow so we can all talk about.

I got the music to work!

**Comment by RobertBohlman** [comment]
Okay I'm gonna upload the betting methods along with the tester class in case anyone wants to demo.

**Comment by Coolcoderguy** [comment]
ok awesome

**Comment by RobertBohlman** [comment]
I think its safe to close this since most of it is done and worked in. If someone feels the need to reopen it feel free.

**Comment by Coolcoderguy** [comment]
can someone call me please at 253 324 0342 right now  I don't know whats going on????
