### ISSUE TITLE
Additional

### ISSUE THREAD

**Issue by RobertBohlman** [ofHillsAndLakes/Project-Juliet-Omicron#7]

**Comment by ofHillsAndLakes** [comment]
Absolutely possible, just slotted in right under the triggering line of code. E.G. right when we output text that says "You Lost!", the next line calls the sound-board method and makes the sound play.

**Comment by RobertBohlman** [comment]
Awesome, I can handle this if that's okay with you David, I needed some more stuff to do anyways.
